Fix wrong version for amppackager 1.0.1 instead of 1.0.2
banaag/click-to-deploy pull request #11
Opened 2020-10-08 00:54 UTC by banaag

Fix wrong version for amppackager 1.0.1 instead of 1.0.2

2020-10-08 23:42 UTC, twifkak requested changes

2020-10-08 23:42 UTC, twifkak commented on docker/amppackager/1/debian10/1.0.1/Dockerfile
> +# limitations under the License.# Use an official Go runtime as a parent image
Newline got squashed here for some reason. I see this happened with the "FROM" line previously. Some weirdness in how template files are interpreted?

2020-10-08 23:42 UTC, twifkak commented on docker/amppackager/1/debian10/1.0.1/Dockerfile
No longer need to do `as certs`, since this is the final build?

2020-10-08 23:42 UTC, twifkak commented on docker/amppackager/init/amppkg_renewer_template.toml
> +    # Uncomment if you need wildcard domains in your certs
If this comment is seen by users, we should also mention the need to build with the arg `-tags dns01` per https://github.com/ampproject/amppackager/blob/ca6f35a1b2e65f02f8e55c9e9bc218f25b801dc8/packager/certfetcher/dns.go#L1

2020-10-08 23:42 UTC, twifkak commented on docker/amppackager/templates/init/amppkg_renewer_template.toml
> +    # Uncomment if you need wildcard domains in your certs
Ditto.

2020-10-08 23:46 UTC, banaag commented on docker/amppackager/1/debian10/1.0.1/Dockerfile
> +# limitations under the License.# Use an official Go runtime as a parent image
Yeah there's this utility called dockerfiles that's a little buggy.

2020-10-08 23:48 UTC, banaag commented on docker/amppackager/1/debian10/1.0.1/Dockerfile
Good catch, removed.

2020-10-08 23:50 UTC, banaag commented on docker/amppackager/init/amppkg_renewer_template.toml
> +    # Uncomment if you need wildcard domains in your certs
Technically won't be seen by users, but probably not a bad idea to add the comment anyway.

2020-10-08 23:50 UTC, banaag commented on docker/amppackager/templates/init/amppkg_renewer_template.toml
> +    # Uncomment if you need wildcard domains in your certs
Ditto.

2020-10-09 00:01 UTC, twifkak approved these changes

2020-10-09 00:04 UTC, merged